databases:
  - name: postgres-db
    plan: free

services:
  # Backend Service (Java)
  - name: backend-app
    type: web
    plan: free
    env: docker
    image:
      url: ghcr.io/relax1205/hr_scanner/backend:latest
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: postgres-db
          property: connectionString
      - key: OPENROUTER_API_KEY
        sync: false

  # Frontend Service (Node.js)
  - name: frontend-app
    type: web
    plan: free
    env: docker
    image:
      url: ghcr.io/relax1205/hr_scanner/frontend:latest
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false